%This function is used to test the MSD of a chain with one bead lay on the
%boundary;This beads can be either fixed or moved on the boudary;
%During the simulation ,the beads move on the boundary when numSimulation
%is pair,or it'll be fixed on the boundary;

frameWorksParams = SimulationFrameworkParams('numSimulations',100,'numSteps',5000,'showSimulation',true,'dt',0.1,...
                    'numChains',1,'objectInteraction',false,'dimension',3,...
                     'encounterDist',sqrt(3)/5,'recordData','true','recipeFileName','rcpRelaxationTimeBeadsOnBoundary');

%define a domain
diffConst = 0.1;
sphereForce = ForceManagerParams('diffusionForce',true,'diffusionConst',diffConst,...
                                 'lennardJonesForce',false,'LJPotentialWidth',0.01,'LJPotentialDepth',0.01,'dt',...
                                  frameWorksParams.simulator.dt);
dp          = DomainHandlerParams('domainShape','sphere','forceParams',sphereForce,'showDomain',true,'domainWidth',...
                                  25,'dt',frameWorksParams.simulator.dt,'diffusionConst',diffConst);
                              
dh          =DomainHandler(dp);                             
%define a chain;

chainForce  = ForceManagerParams('springForce',true,'diffusionForce',true,'diffusionConst',diffConst,...
                                 'bendingElasticityForce',false,'bendingConst',0.1,...
                                 'springConst',1,...
                                 'minParticleEqDistance',0);
 initialPt = dh.GetRandomBoundarySample(1);
 
cp(1)= ChainParams('numBeads',64,'initializeInDomain',1,'springForce',true,...
                   'fixedBeadNum',1,'fixedBeadsPosition',initialPt,'diffusionConst',0.1,...
                   'forceParams',chainForce,...
                   'b', sqrt(frameWorksParams.simulator.dimension),...
                   'dt',frameWorksParams.simulator.dt,...
                   'beadsOnBoundary',[1],...
                   'maxStepsOnBoundaryPerTime', 10); 
               
frameWorksParams.SetDomainParams(dp);
frameWorksParams.SetChainParams(cp);
% initialize simulator framework
r = RouseSimulatorFramework(frameWorksParams);
r.Run;
%run;



